spring:
  jmx:
    enabled: false
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:h2:file:~/testdb;NON_KEYWORDS=USER
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    user: sa
    password: password
    locations:
      - classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
